version: '3.4'

services:
  db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: Passw0rd!
  throneteki.lobbynode:
    image: ${DOCKER_REGISTRY-}thronetekilobbynode
    build:
      context: .
      dockerfile: Dockerfile
